// app/dev-hub/page.tsx
"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabaseClient";

type TokenRow = {
  id: string;
  name: string;
  symbol: string;
  description: string | null;
  image_url: string | null;
  telegram_url: string | null;
  x_url: string | null;
  website_url: string | null;
  created_at: string;
};

const supabase = createClient();

export default function DevHubPage() {
  // Form state
  const [name, setName] = useState("");
  const [symbol, setSymbol] = useState("");
  const [description, setDescription] = useState("");
  const [imageUrl, setImageUrl] = useState("");
  const [telegramUrl, setTelegramUrl] = useState("");
  const [xUrl, setXUrl] = useState("");
  const [websiteUrl, setWebsiteUrl] = useState("");

  const [submitting, setSubmitting] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);
  const [formSuccess, setFormSuccess] = useState<string | null>(null);

  // Latest tokens
  const [tokens, setTokens] = useState<TokenRow[]>([]);
  const [loadingTokens, setLoadingTokens] = useState(true);
  const [tokensError, setTokensError] = useState<string | null>(null);

  const fetchTokens = async () => {
    setLoadingTokens(true);
    setTokensError(null);
    const { data, error } = await supabase
      .from("tokens")
      .select("*")
      .order("created_at", { ascending: false })
      .limit(10);

    if (error) {
      console.error(error);
      setTokensError(error.message);
      setTokens([]);
    } else {
      setTokens((data as TokenRow[]) || []);
    }
    setLoadingTokens(false);
  };

  useEffect(() => {
    fetchTokens();
  }, []);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setFormError(null);
    setFormSuccess(null);

    const trimmedName = name.trim();
    const trimmedSymbol = symbol.trim();

    if (!trimmedName || !trimmedSymbol) {
      setFormError("Token name and symbol are required.");
      return;
    }

    setSubmitting(true);

    const { error } = await supabase.from("tokens").insert([
      {
        // id is generated by Supabase if your column has a default
        name: trimmedName,
        symbol: trimmedSymbol.toUpperCase(),
        description: description || null,
        image_url: imageUrl || null,
        telegram_url: telegramUrl || null,
        x_url: xUrl || null,
        website_url: websiteUrl || null,
      },
    ]);

    setSubmitting(false);

    if (error) {
      console.error(error);
      setFormError(error.message || "Failed to create token.");
      return;
    }

    setFormSuccess("Token profile created and saved to Supabase.");
    setName("");
    setSymbol("");
    setDescription("");
    setImageUrl("");
    setTelegramUrl("");
    setXUrl("");
    setWebsiteUrl("");

    // Refresh latest tokens list
    fetchTokens();
  };

  return (
    <main className="min-h-screen bg-slate-950 text-slate-100">
      <div className="max-w-5xl mx-auto px-4 py-10 sm:py-16 space-y-10">
        {/* Header */}
        <header className="border-b border-slate-800 pb-6">
          <p className="text-xs uppercase tracking-[0.25em] text-cyan-400">
            Cyber Dev Token • $CDT
          </p>
          <h1 className="mt-3 text-3xl sm:text-4xl font-bold text-slate-50">
            Cyber Dev Token Hub
          </h1>
          <p className="mt-3 text-sm sm:text-base text-slate-300 max-w-2xl">
            Create your token profile below. Upload an image or paste a URL.
            Every token gets its own portal page where the community can talk.
          </p>
        </header>

        {/* Create Token Form */}
        <section className="grid gap-8 lg:grid-cols-[minmax(0,2fr)_minmax(0,1.4fr)] items-start">
          <form
            onSubmit={handleSubmit}
            className="space-y-4 rounded-2xl border border-slate-800 bg-slate-900/50 p-4 sm:p-6"
          >
            <h2 className="text-lg font-semibold text-slate-50 mb-1">
              Create Token Profile
            </h2>
            <p className="text-xs text-slate-400 mb-3">
              This writes directly into the <span className="font-mono">tokens</span> table on Supabase.
            </p>

            {formError && (
              <div className="rounded-md border border-red-700 bg-red-900/40 px-3 py-2 text-xs text-red-100">
                {formError}
              </div>
            )}

            {formSuccess && (
              <div className="rounded-md border border-emerald-700 bg-emerald-900/40 px-3 py-2 text-xs text-emerald-100">
                {formSuccess}
              </div>
            )}

            <div className="space-y-1">
              <label className="text-xs font-medium text-slate-200">
                Token Name
              </label>
              <input
                type="text"
                className="w-full rounded-md border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-100 outline-none focus:border-cyan-500"
                placeholder="Cyber Dev Token"
                value={name}
                onChange={(e) => setName(e.target.value)}
              />
            </div>

            <div className="space-y-1">
              <label className="text-xs font-medium text-slate-200">
                Symbol
              </label>
              <input
                type="text"
                className="w-full rounded-md border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-100 outline-none focus:border-cyan-500"
                placeholder="CDT"
                value={symbol}
                onChange={(e) => setSymbol(e.target.value)}
              />
            </div>

            <div className="space-y-1">
              <label className="text-xs font-medium text-slate-200">
                Description
              </label>
              <textarea
                className="w-full rounded-md border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-100 outline-none focus:border-cyan-500 min-h-[80px]"
                placeholder="Short description of what this token is building."
                value={description}
                onChange={(e) => setDescription(e.target.value)}
              />
            </div>

            {/* Image URL only (keep it simple for now) */}
            <div className="space-y-1">
              <label className="text-xs font-medium text-slate-200">
                Token Image URL (optional)
              </label>
              <input
                type="url"
                className="w-full rounded-md border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-100 outline-none focus:border-cyan-500"
                placeholder="https://example.com/image.png"
                value={imageUrl}
                onChange={(e) => setImageUrl(e.target.value)}
              />
            </div>

            <div className="grid gap-3 sm:grid-cols-2">
              <div className="space-y-1">
                <label className="text-xs font-medium text-slate-200">
                  Telegram URL
                </label>
                <input
                  type="url"
                  className="w-full rounded-md border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-100 outline-none focus:border-cyan-500"
                  placeholder="https://t.me/your_project"
                  value={telegramUrl}
                  onChange={(e) => setTelegramUrl(e.target.value)}
                />
              </div>
              <div className="space-y-1">
                <label className="text-xs font-medium text-slate-200">
                  X (Twitter) URL
                </label>
                <input
                  type="url"
                  className="w-full rounded-md border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-100 outline-none focus:border-cyan-500"
                  placeholder="https://x.com/your_project"
                  value={xUrl}
                  onChange={(e) => setXUrl(e.target.value)}
                />
              </div>
            </div>

            <div className="space-y-1">
              <label className="text-xs font-medium text-slate-200">
                Website URL
              </label>
              <input
                type="url"
                className="w-full rounded-md border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-100 outline-none focus:border-cyan-500"
                placeholder="https://yourproject.xyz"
                value={websiteUrl}
                onChange={(e) => setWebsiteUrl(e.target.value)}
              />
            </div>

            <button
              type="submit"
              disabled={submitting}
              className="mt-2 inline-flex items-center justify-center rounded-md bg-cyan-500 px-4 py-2 text-sm font-medium text-slate-950 hover:bg-cyan-400 disabled:opacity-60 disabled:cursor-not-allowed transition-colors"
            >
              {submitting ? "Creating..." : "Create Token Profile"}
            </button>
          </form>

          {/* Live preview */}
          <div className="space-y-3">
            <div className="rounded-2xl border border-slate-800 bg-slate-900/40 p-4">
              <h2 className="text-sm font-semibold text-slate-50 mb-2">
                Preview
              </h2>
              <div className="flex items-start gap-3">
                <div className="h-10 w-10 rounded-full border border-slate-700 bg-slate-900 flex items-center justify-center text-[10px] text-slate-400 overflow-hidden">
                  {imageUrl ? (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img
                      src={imageUrl}
                      alt="Token preview"
                      className="h-full w-full object-cover"
                    />
                  ) : (
                    <span>IMG</span>
                  )}
                </div>
                <div className="space-y-1">
                  <p className="text-sm font-semibold text-slate-50">
                    {name || "Your Token Name"}
                  </p>
                  <p className="text-xs text-cyan-300 font-mono">
                    {symbol || "SYM"}
                  </p>
                  <p className="text-xs text-slate-400">
                    {description ||
                      "This is where your token description will appear."}
                  </p>
                  <p className="text-[11px] text-slate-500">
                    {websiteUrl || xUrl || telegramUrl
                      ? "Links will show on the portal."
                      : "No links added yet."}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Latest Tokens */}
        <section className="border-t border-slate-800 pt-6 space-y-4">
          <div className="flex items-center justify-between gap-2">
            <h2 className="text-base sm:text-lg font-semibold text-slate-50">
              Latest Tokens
            </h2>
            <Link
              href="/directory"
              className="text-xs text-cyan-400 hover:text-cyan-300 underline"
            >
              View full directory
            </Link>
          </div>

          {loadingTokens && (
            <p className="text-xs text-slate-400">Loading tokens…</p>
          )}

          {tokensError && (
            <p className="text-xs text-red-400">
              Error loading tokens: {tokensError}
            </p>
          )}

          {!loadingTokens && !tokensError && tokens.length === 0 && (
            <p className="text-xs text-slate-400">
              No tokens yet. Once you create a profile, it will appear here.
            </p>
          )}

          <div className="grid gap-4 sm:grid-cols-2">
            {tokens.map((token) => (
              <Link
                key={token.id}
                href={`/tokens/${encodeURIComponent(token.id)}`}
                className="group border border-slate-800 rounded-2xl p-4 bg-slate-900/40 hover:bg-slate-900/70 hover:border-cyan-500/70 transition-colors"
              >
                <div className="flex items-start gap-3">
                  <div className="h-10 w-10 rounded-full border border-slate-700 bg-slate-900 flex items-center justify-center text-[10px] text-slate-400 overflow-hidden">
                    {token.image_url ? (
                      // eslint-disable-next-line @next/next/no-img-element
                      <img
                        src={token.image_url}
                        alt={token.name || ""}
                        className="h-full w-full object-cover"
                      />
                    ) : (
                      <span>{token.symbol || "SYM"}</span>
                    )}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-semibold text-slate-50 truncate">
                      {token.name || "Untitled Token"}
                    </p>
                    <p className="text-xs text-cyan-300 font-mono mb-1">
                      {token.symbol || "—"}
                    </p>
                    <p className="text-xs text-slate-400 line-clamp-2">
                      {token.description || "No description provided yet."}
                    </p>
                    <p className="mt-2 text-[11px] text-cyan-300 opacity-0 group-hover:opacity-100 transition-opacity">
                      Open portal →{" "}
                      <span className="text-slate-300">
                        enter this project&apos;s room
                      </span>
                    </p>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </section>
      </div>
    </main>
  );
}
